### ISSUE TITLE
Examples for how to confirm session and close session?

### ISSUE THREAD

**Issue by Autre31415** [AngryBytes/portier-node#2]
Following the example shown here I was able to authenticate an email address on the public portier server successfully, but the missing piece for me is how to confirm that session on other routes, and how to close out a session.

**Comment by onli** [comment]
I think what you are missing is https://github.com/expressjs/session. After you authenticate the user via portier, set a session variable that contains his email. That variable you can check in all other routes.

Untested code: 

```
app.post('/verify', formParser, (req, res, next) => {
    portier.verify(req.body.id_token, (err, email) => {
        if (err) return next(err);
        req.session.authorized_email = email;
        res.type('html').end(`
            <p>Verified email address ${email}!</p>
        `);
    });
});
```

To logout drop that session, with `req.session.destroy`.
